
# Changing default LLM
embabel.models.default-llm=qwen3.6-flash
embabel.models.default-embedding-model=text-embedding-v3

# Llm Roles: Create as many as you want and use with byRole("role-name")
#embabel.models.llms.best=llama3.1:8b
#embabel.models.llms.cheapest=llama3.1:8b

#embabel.models.embedding-services.best=nomic-embed-text:latest
#embabel.models.embedding-services.cheapest=nomic-embed-text:latest

embabel.agent.platform.models.openai.custom.base-url=https://dashscope.aliyuncs.com/compatible-mode
embabel.agent.platform.models.openai.custom.api-key=${DASHSCOPE_API_KEY}
embabel.agent.platform.models.openai.custom.models=qwen3.6-flash,deepseek-v4-flash,qwen3.7-max,qwen3.6-27b

embabel.agent.platform.ranking.llm=qwen3.6-27b
embabel.agent.platform.llm-operations.prompts.generate-examples-by-default=false

#embabel.agent.logging.personality=starwars

#spring.ai.ollama.chat.options.format=json

#spring.ai.openai.base-url=https://dashscope.aliyuncs.com/compatible-mode/v1
#spring.ai.openai.api-key=${DASHSCOPE_API_KEY}
